global:
  slack_api_url: 'https://hooks.slack.com/services/XXXXXXXXX/XXXXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXX'

route:
  group_wait: 10s
  group_interval: 5m
  receiver: 'default-receiver'

receivers:
  - name: 'default-receiver'
    slack_configs:
      - send_resolved: true
        text: 'Alert: {{ .CommonAnnotations.summary }}'