version: '3.8'

services:
  prometheus:
    image: prom/prometheus:v2.50.1
    mem_limit: 4G
    cpus: 2
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - ./prom_data:/prometheus/data
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  alertmanager:
    image: prom/alertmanager:v0.27.0
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager:/etc/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    depends_on:
      - prometheus

  grafana:
    image: grafana/grafana:10.0.12-ubuntu
    mem_limit: 4G
    cpus: 2
    ports:
      - 3000:3000
    volumes:
      # - ./grafana:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

# volumes:
#   prometheus_data:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: /path/to/local/disk