global:
  scrape_interval: 15s

scrape_configs:
  # - job_name: 'win_vms'
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets:
  #         - '223.169.100.101:9182'

  - job_name: 'prom'
    scrape_interval: 5s
    static_configs:
      - targets:
          - 'prometheus:9090'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'
