global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['223.169.100.101:9182', '223.169.100.102:9182']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']